//
// OpenVRML
//
// Copyright (C) 1998  Chris Morley
// 
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
// 
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
// 

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

#if defined(_WIN32) && !defined(__CYGWIN__)
#include <winconfig.h>
#endif

#include <algorithm>
#include <errno.h>
#include <stdio.h>
#if defined(_WIN32) && !defined(__CYGWIN__)
#include <strstrea.h>
#else
#include <strstream.h>
#endif
#include "VrmlScene.h"
#include "doc2.hpp"
#include "Viewer.h"
#include "System.h"
#include "MathUtils.h"
#include "VrmlNamespace.h"
#include "VrmlRenderContext.h"
#include "script.h"

//
// Including a .cpp file is strange, but it's exactly what we want to do here.
// This usage lets us put the ANTLR parser in an unnamed namespace.
//
#include "Vrml97Parser.cpp"
} // Close "namespace OpenVRML", opened in Vrml97Parser.cpp.

// Max time in seconds between updates. Make this user
// setable to balance performance with cpu usage.
#ifndef DEFAULT_DELTA
#define DEFAULT_DELTA 0.5
#endif

/**
 * @namespace OpenVRML
 * 
 * @brief The OpenVRML Runtime Library
 */
namespace OpenVRML {

/**
 * @typedef NodeClassMap
 *
 * @brief Maps URIs to @link NodeClass NodeClasses@endlink.
 */


/**
 * @class VrmlScene
 *
 * @brief Encapsulates a VRML scene.
 */

/**
 * @var VrmlScene::Vrml97Parser
 *
 * @brief VRML97 parser generated by ANTLR.
 */

/**
 * @var VrmlScene::ProtoNodeClass
 *
 * @brief Class object for @link ProtoNodes@endlink.
 */

/**
 * @var VrmlScene::Vrml97Node::Inline
 *
 * @brief VRML97 Inline node.
 *
 * @todo Fix Inline nodes.
 */

/**
 * @enum VrmlScene::CBReason
 *
 * @brief Valid reasons for scene callback.
 */

/**
 * @var VrmlScene::CBReason VrmlScene::DESTROY_WORLD
 *
 * @brief Destroy the world.
 */

/**
 * @var VrmlScene::CBReason VrmlScene::REPLACE_WORLD
 *
 * @brief Replace the world.
 */

/**
 * @typedef VrmlScene::SceneCB
 *
 * @brief A pointer to a scene callback function.
 *
 * The callback function provoides a way to let the app know when a world is
 * loaded, changed, etc.
 */

/**
 * @var NodeClassMap VrmlScene::nodeClassMap
 *
 * @brief A map of URIs to node implementations.
 */

/**
 * @var ScriptNodeClass VrmlScene::scriptNodeClass
 *
 * @brief NodeClass for Script nodes in the scene.
 */

/**
 * @var Doc2 * VrmlScene::d_url
 *
 * @brief Doc2 object associated with the scene.
 */

/**
 * @var MFNode VrmlScene::nodes
 *
 * @brief The root nodes for the scene.
 */

/**
 * @var VrmlNamespace * VrmlScene::scope
 *
 * @brief The root scope for the scene.
 */

/**
 * @typedef VrmlScene::BindStack
 *
 * @brief A list of bound nodes.
 */

/**
 * @var VrmlScene::BindStack VrmlScene::d_backgroundStack
 *
 * @brief The stack of bound Background nodes.
 */

/**
 * @var VrmlScene::BindStack VrmlScene::d_fogStack
 *
 * @brief The stack of bound Fog nodes.
 */

/**
 * @var VrmlScene::BindStack VrmlScene::d_navigationInfoStack
 *
 * @brief The stack of bound NavigationInfo nodes.
 */

/**
 * @var VrmlScene::BindStack VrmlScene::d_viewpointStack
 *
 * @brief The stack of bound Viewpoint nodes.
 */

/**
 * @var std::list<Node *> VrmlScene::d_backgrounds
 *
 * @brief A list of all the Background nodes in the scene.
 */

/**
 * @var std::list<Node *> VrmlScene::d_fogs
 *
 * @brief A list of all the Fog nodes in the scene.
 */

/**
 * @var std::list<Node *> VrmlScene::d_navigationInfos
 *
 * @brief A list of all the NavigationInfo nodes in the scene.
 */

/**
 * @var std::list<Node *> VrmlScene::d_viewpoints
 *
 * @brief A list of all the Viewpoint nodes in the scene.
 */

/**
 * @var std::list<Node *> VrmlScene::d_scopedLights
 *
 * @brief A list of all the scoped light nodes in the scene.
 */

/**
 * @var std::list<ScriptNode *> VrmlScene::d_scripts
 *
 * @brief A list of all the Script nodes in the scene.
 */

/**
 * @var std::list<Node *> VrmlScene::d_timers
 *
 * @brief A list of all the TimeSensor nodes in the scene.
 */

/**
 * @var std::list<Node *> VrmlScene::d_audioClips
 *
 * @brief A list of all the AudioClip nodes in the scene.
 */

/**
 * @var std::list<Node *> VrmlScene::d_movies
 *
 * @brief A list of all the MovieTexture nodes in the scene.
 */

/**
 * @var std::list<Node *> VrmlScene::protoNodeList
 *
 * @brief A list of all the prototype nodes in the scene.
 */

/**
 * @var bool VrmlScene::d_modified
 *
 * @brief Flag to indicate whether the scene has been modified.
 */

/**
 * @var bool VrmlScene::d_newView
 *
 * @brief Flag to indicate if the user has changed to a new view.
 */

/**
 * @var double VrmlScene::d_deltaTime
 *
 * @brief Time elapsed since the last update.
 */

/**
 * @typedef VrmlScene::SceneCBList
 *
 * @brief List of functions to call when the world is changed.
 */

/**
 * @struct VrmlScene::Event
 *
 * @brief An event.
 *
 * An event has a value and a destination, and is associated with a time.
 */

/**
 * @var double VrmlScene::Event::timeStamp
 *
 * @brief The timestamp of the event.
 */

/**
 * @var FieldValue * VrmlScene::Event::value
 *
 * @brief The value associated with the event.
 */

/**
 * @var NodePtr VrmlScene::Event::toNode
 *
 * @brief The Node the event is going to.
 */

/**
 * @var std::string VrmlScene::Event::toEventIn
 *
 * @brief The eventIn of @a toNode the event is going to.
 */

/**
 * @var MFString * VrmlScene::d_pendingUrl
 *
 * @brief Allow requests to load URLs; nodes to wait until all events are
 *      processed.
 */

/**
 * @var MFString * VrmlScene::d_pendingParameters
 *
 * @brief Parameters associated with @a d_pendingNodes.
 */

/**
 * @var VrmlScene::SceneCBList VrmlScene::d_sceneCallbacks
 *
 * @brief List of functions to call when the world is changed.
 */

/**
 * @var double VrmlScene::d_frameRate
 *
 * @brief Frame rate.
 */

/**
 * @var VrmlScene::MAXEVENTS
 *
 * @brief The maximum number of events which may be queued.
 *
 * Each scene can have a limited number of pending events.
 * Repeatedly allocating/freeing events is slow (it would be
 * nice to get rid of the field cloning, too), and if there are
 * so many events pending, we are probably running too slow to
 * handle them effectively anyway.
 */

/**
 * @var VrmlScene::Event VrmlScene::d_eventMem
 *
 * @brief The event queue.
 *
 * @todo The event queue ought to be sorted by timeStamp.
 */

/**
 * @var bool VrmlScene::d_flags_need_updating
 *
 * @brief Set by Node::setBVolumeDirty on any node in this scene graph,
 *      cleared by updateFlags.
 *
 * @c true if the bvolume dirty flag has been set on a node in the
 * scene graph, but has not yet been propegated to that node's
 * ancestors. 
 */

/**
 * @brief Create a VrmlScene from a URI.
 *
 * @param url   a URI.
 */
VrmlScene::VrmlScene(const std::string & url):
        scriptNodeClass(*this), d_flags_need_updating(false),
        d_url(new Doc2(url)), scope(0), d_modified(false), d_newView(false),
        d_deltaTime(DEFAULT_DELTA), d_pendingUrl(0), d_pendingParameters(0),
        d_pendingNodes(0), d_pendingScope(0), d_frameRate(0.0), d_firstEvent(0),
        d_lastEvent(0) {
    this->initNodeClassMap();
    this->scope = new Vrml97RootNamespace(this->nodeClassMap);

    MFNode * newNodes = this->readWrl(this->d_url, this->scope);
    if (newNodes) {
        this->nodes = *newNodes;
        
        for (size_t i = 0; i < this->nodes.getLength(); ++i) {
            this->nodes.getElement(i)->accumulateTransform(0);
        }
    }
    delete newNodes;

    const double timeNow = theSystem->time();
    
    //
    // Initialize Script nodes.
    //
    std::for_each(this->d_scripts.begin(), this->d_scripts.end(),
                  std::bind2nd(std::mem_fun(&ScriptNode::initialize), timeNow));
    
    //
    // Send initial bind events to bindable nodes.
    //
    if (!this->d_backgrounds.empty()) {
        assert(this->d_backgrounds.front());
        this->d_backgrounds.front()
                ->processEvent("set_bind", SFBool(true), timeNow);
    }
    
    if (!this->d_fogs.empty()) {
        assert(this->d_fogs.front());
        this->d_fogs.front()->processEvent("set_bind", SFBool(true), timeNow);
    }
    
    if (!this->d_navigationInfos.empty()) {
        assert(this->d_navigationInfos.front());
        this->d_navigationInfos.front()
                ->processEvent("set_bind", SFBool(true), timeNow);
    }
    
    if (!this->d_viewpoints.empty()) {
        assert(this->d_viewpoints.front());
        this->d_viewpoints.front()
                ->processEvent("set_bind", SFBool(true), timeNow);
    }
    
    this->setModified();
    this->d_newView = true;		// Force resetUserNav
}

/**
 * @brief Destructor.
 */
VrmlScene::~VrmlScene() {
    delete d_url;

    delete d_pendingUrl;
    delete d_pendingParameters;
    delete d_pendingNodes;
    delete d_pendingScope;

    delete this->scope;
}

/**
 * @brief Get the browser name.
 *
 * @return "%OpenVRML"
 *
 * Specific browsers may wish to override this method.
 */
const char * VrmlScene::getName() { return "OpenVRML"; }

/**
 * @brief Get the browser version.
 *
 * @return the version of OpenVRML.
 *
 * Specific browsers may wish to override this method.
 */
const char * VrmlScene::getVersion() { return PACKAGE_VERSION; }

/**
 * @brief Initialize the NodeClass map with the available node implementations.
 */
void VrmlScene::initNodeClassMap() {
    this->nodeClassMap["urn:openvrml:node:Script"] =
            NodeClassPtr(new ScriptNodeClass(*this));
    
    using namespace Vrml97Node;
    this->nodeClassMap["urn:X-openvrml:node:Anchor"] =
            NodeClassPtr(new AnchorClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:Appearance"] =
            NodeClassPtr(new AppearanceClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:AudioClip"] =
            NodeClassPtr(new AudioClipClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:Background"] =
            NodeClassPtr(new BackgroundClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:Billboard"] =
            NodeClassPtr(new BillboardClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:Box"] =
            NodeClassPtr(new BoxClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:Collision"] =
            NodeClassPtr(new CollisionClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:Color"] =
            NodeClassPtr(new ColorClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:ColorInterpolator"] =
            NodeClassPtr(new ColorInterpolatorClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:Cone"] =
            NodeClassPtr(new ConeClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:Coordinate"] =
            NodeClassPtr(new CoordinateClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:CoordinateInterpolator"] =
            NodeClassPtr(new CoordinateInterpolatorClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:Cylinder"] =
            NodeClassPtr(new CylinderClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:CylinderSensor"] =
            NodeClassPtr(new CylinderSensorClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:DirectionalLight"] =
            NodeClassPtr(new DirectionalLightClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:ElevationGrid"] =
            NodeClassPtr(new ElevationGridClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:Extrusion"] =
            NodeClassPtr(new ExtrusionClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:Fog"] =
            NodeClassPtr(new FogClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:FontStyle"] =
            NodeClassPtr(new FontStyleClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:Group"] =
            NodeClassPtr(new GroupClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:ImageTexture"] =
            NodeClassPtr(new ImageTextureClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:IndexedFaceSet"] =
            NodeClassPtr(new IndexedFaceSetClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:IndexedLineSet"] =
            NodeClassPtr(new IndexedLineSetClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:Inline"] =
            NodeClassPtr(new InlineClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:LOD"] =
            NodeClassPtr(new LODClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:Material"] =
            NodeClassPtr(new MaterialClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:MovieTexture"] =
            NodeClassPtr(new MovieTextureClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:NavigationInfo"] =
            NodeClassPtr(new NavigationInfoClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:Normal"] =
            NodeClassPtr(new NormalClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:NormalInterpolator"] =
            NodeClassPtr(new NormalInterpolatorClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:OrientationInterpolator"] =
            NodeClassPtr(new OrientationInterpolatorClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:PixelTexture"] =
            NodeClassPtr(new PixelTextureClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:PlaneSensor"] =
            NodeClassPtr(new PlaneSensorClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:PointLight"] =
            NodeClassPtr(new PointLightClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:PointSet"] =
            NodeClassPtr(new PointSetClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:PositionInterpolator"] =
            NodeClassPtr(new PositionInterpolatorClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:ProximitySensor"] =
            NodeClassPtr(new ProximitySensorClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:ScalarInterpolator"] =
            NodeClassPtr(new ScalarInterpolatorClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:Shape"] =
            NodeClassPtr(new ShapeClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:Sound"] =
            NodeClassPtr(new SoundClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:Sphere"] =
            NodeClassPtr(new SphereClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:SphereSensor"] =
            NodeClassPtr(new SphereSensorClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:SpotLight"] =
            NodeClassPtr(new SpotLightClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:Switch"] =
            NodeClassPtr(new SwitchClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:Text"] =
            NodeClassPtr(new TextClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:TextureCoordinate"] =
            NodeClassPtr(new TextureCoordinateClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:TextureTransform"] =
            NodeClassPtr(new TextureTransformClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:TimeSensor"] =
            NodeClassPtr(new TimeSensorClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:TouchSensor"] =
            NodeClassPtr(new TouchSensorClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:Transform"] =
            NodeClassPtr(new TransformClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:Viewpoint"] =
            NodeClassPtr(new ViewpointClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:VisibilitySensor"] =
            NodeClassPtr(new VisibilitySensorClass(*this));
    this->nodeClassMap["urn:X-openvrml:node:WorldInfo"] =
            NodeClassPtr(new WorldInfoClass(*this));
}

/**
 * @brief Get the root nodes for the scene.
 *
 * @return the root nodes for the scene.
 */
const MFNode & VrmlScene::getRootNodes() const throw () { return this->nodes; }

/**
 * @brief Load a (possibly non-VRML) file...
 */
bool VrmlScene::loadUrl(const MFString & url,
                        const MFString & parameters) {
    
    size_t np = parameters.getLength();
    
    // try each url until we find one we can handle
    size_t i(0);
    for (; i < url.getLength(); ++i) {
        using std::string;
        const string & currentUrl = url.getElement(i);
        if (currentUrl.length() == 0) {
            continue;
        }
        
# if 0
        // #Viewpoint
        if (currentUrl[0] == '#') {
            if (load(url.getElement(i))) {
                break;
            }
        }
# endif
        
        // Load .wrl's, or pass off to system
        else {
            // Check mime type...
            string::size_type tailPos = currentUrl.find_last_of('/');
            if (tailPos == string::npos) {
                tailPos = 0;
            }
            string::size_type modPos = currentUrl.find_first_of('#', tailPos);
            if (modPos == string::npos) {
                modPos = currentUrl.length();
            }
            if (modPos - tailPos > 4
                    && (currentUrl.substr(modPos - 4, 4) == ".wrl"
                        || currentUrl.substr(modPos - 4, 4) == ".wrz"
                        || currentUrl.substr(modPos - 4, 4) == ".WRL"
                        || currentUrl.substr(modPos - 4, 4) == ".WRZ"
                        || (modPos - tailPos > 7 && currentUrl.substr(modPos - 7, 7) == ".wrl.gz")))
            {
# if 0
                if (load(currentUrl)) {
                    break;
                }
# endif
	    } else {
                if (theSystem->loadUrl(currentUrl, parameters)) {
                    break;
                }
            }
        }
    }
    
    return (i != url.getLength());  // true if we found a url that loaded
}

/**
 * @brief Execute scene callback functions.
 *
 * @param reason    the CBReason to pass to the callback functions.
 */
void VrmlScene::doCallbacks(const CBReason reason) {
  SceneCBList::iterator cb, cbend = d_sceneCallbacks.end();
  for (cb = d_sceneCallbacks.begin(); cb != cbend; ++cb)
    (*cb)( reason );

}

/**
 * @brief Add a callback function to be called when the world changes.
 *
 * @param cb    a scene callback function.
 */
void VrmlScene::addWorldChangedCallback(const SceneCB cb) {
    this->d_sceneCallbacks.push_front(cb);
}

/**
 * @brief Read a VRML file from one of the urls.
 */
MFNode * VrmlScene::readWrl(const MFString & urls, Doc2 * relative,
                            VrmlNamespace * ns) {
    Doc2 url;
    const size_t n = urls.getLength();
    for (size_t i = 0; i < n; ++i) {
        //theSystem->debug("Trying to read url '%s'\n", urls->get(i));
        url.seturl(urls.getElement(i).c_str(), relative );
        MFNode * kids = this->readWrl(&url, ns);
        if (kids) {
            return kids;
        } else if ((i < n - 1)
                && strncmp(urls.getElement(i).c_str(), "urn:", 4)) {
            theSystem->warn("Couldn't read url '%s': %s\n",
                            urls.getElement(i).c_str(), strerror(errno));
        }
    }
    
    return 0;
}


/**
 * @brief Read a VRML file and return the (valid) nodes.
 */
MFNode * VrmlScene::readWrl(Doc2 * tryUrl, VrmlNamespace * ns) {
    MFNode * result = 0;
    
    // Should verify MIME type...
    istream & istm = tryUrl->inputStream();
    if (istm) {
        
        Vrml97Scanner scanner(istm);
        Vrml97Parser parser(scanner);
        
        //
        // If the caller is not interested in PROTO defs, use a local namespace.
        //
        // Note: Can we displace the responsibility for this to the caller? Here
        // we instantiate a VrmlNamespace whether or not we need it. That could
        // be avoided with new/delete, but the resulting code would be awkward
        // and hard to follow. Why not instead have the caller pass in a
        // reference to a namespace, and let the caller decide whether or not a
        // new namespace should be instantiated?
        // -- Braden McDaniel <braden@endoframe.com>, 30 Mar, 2000
        //
        VrmlNamespace nodeDefs;
        VrmlNamespace * rootNamespace = ns ? ns : &nodeDefs;
        
        result = new MFNode();
        parser.vrmlScene(*this, *result, *rootNamespace, tryUrl);
    }
    
    return result;
}

/**
 * @brief Read VRML from a string and return the (valid) nodes.
 */
const MFNode VrmlScene::readString(char const * vrmlString, VrmlNamespace * ns)
{
    //
    // Hmm. It looks like passing a zero pointer for the namespace argument of
    // this function is not an option. Perhaps it should be a reference rather
    // than a pointer?
    // -- Braden McDaniel <braden@endoframe.com> 1 Apr, 2000
    //
    
    MFNode result;
    
    if (vrmlString) {
        istrstream istrstm(
#ifdef _WIN32
                           const_cast<char *>(vrmlString)
#else
                           vrmlString
#endif
                           );
        Vrml97Scanner scanner(istrstm);
        Vrml97Parser parser(scanner);
        parser.vrmlScene(*this, result, *ns, 0);
    }
    
    return result;
}

/**
 * @brief Write the current scene to a file.
 *
 * @todo Need to save the PROTOs/EXTERNPROTOs too...
 */
bool VrmlScene::save(const char *url)
{
  bool success = false;
  Doc2 save(url);
  ostream &os = save.outputStream();

  if (os)
    {
      os << "#VRML V2.0 utf8\n";
      os << this->nodes;
      success = true;
    }

  return success;
}

/**
 * @brief Get the URI for the current scene.
 *
 * @return the Doc2 associated with the current scene.
 */
Doc2 * VrmlScene::urlDoc() const { return this->d_url; }

/**
 * @brief Get the root scope for the scene.
 *
 * @return the root scope for the scene.
 */
VrmlNamespace * VrmlScene::getScope() const { return this->scope; }

/**
 * @brief Get the current frame rate.
 *
 * @return the current frame rate.
 */
double VrmlScene::getFrameRate() const { return this->d_frameRate; }

/**
 * @brief Queue an event to load a URL (async so it can be called from a node)
 *
 * @param url           a URI.
 * @param parameters    parameters associated with @a url.
 */
void VrmlScene::queueLoadUrl(const MFString & url,
                             const MFString & parameters) {
    if (!this->d_pendingNodes && !this->d_pendingUrl) {
        this->d_pendingUrl = new MFString(url);
        this->d_pendingParameters = new MFString(parameters);
    }
}

/**
 * @brief Queue an event to replace the node for the world.
 *
 * @param nodes the new nodes.
 * @param ns    the scope associated with @a nodes.
 */
void VrmlScene::queueReplaceNodes(const MFNode & nodes, VrmlNamespace & ns) {
    if (!this->d_pendingNodes && !this->d_pendingUrl) {
        this->d_pendingNodes = new MFNode(nodes);
        d_pendingScope = &ns;
    }
}

/**
 * @brief Queue an event for a node.
 *
 * Current events are in the array @a d_eventMem[d_firstEvent,d_lastEvent). If
 * @a d_firstEvent == @a d_lastEvent, the queue is empty. There is a fixed
 * maximum number of events. If we are so far behind that the queue is filled,
 * the oldest events get overwritten.
 */
void VrmlScene::queueEvent(double timeStamp, FieldValue * value,
			   const NodePtr & toNode,
			   const std::string & toEventIn) {
    Event * e = &this->d_eventMem[this->d_lastEvent];
    e->timeStamp = timeStamp;
    e->value = value;
    e->toNode = toNode;
    e->toEventIn = toEventIn;
    d_lastEvent = (d_lastEvent+1) % MAXEVENTS;

    // If the event queue is full, discard the oldest (in terms of when it
    // was put on the queue, not necessarily in terms of earliest timestamp).
    if (d_lastEvent == d_firstEvent) {
        e = &d_eventMem[d_lastEvent];
        delete e->value;
        d_firstEvent = (d_firstEvent+1) % MAXEVENTS;
    }
}

/**
 * @brief Check if any events are waiting to be distributed.
 *
 * @return @true if there are pending events, @c false otherwise.
 */
bool VrmlScene::eventsPending() {
    return this->d_firstEvent != this->d_lastEvent;
}


/**
 * @brief Discard all pending events
 */
void VrmlScene::flushEvents()
{
  while (d_firstEvent != d_lastEvent)
    {
      Event *e = &d_eventMem[d_firstEvent];
      d_firstEvent = (d_firstEvent+1) % MAXEVENTS;
      delete e->value;
    }
}

/**
 * Called by the viewer when the cursor passes over, clicks, drags, or
 * releases a sensitive object (an Anchor or another grouping node with 
 * an enabled TouchSensor child).
 */
void VrmlScene::sensitiveEvent(Node * const n,
                               const double timeStamp,
                               const bool isOver, const bool isActive,
                               double * const point) {
    if (n) {
        Vrml97Node::Anchor * a = n->toAnchor();
        if (a) {
            //
            // This should really be (isOver && !isActive && n->wasActive)
            // (ie, button up over the anchor after button down over the anchor)
            //
            if (isActive && isOver) {
                a->activate();
            } else if (isOver) {
                const std::string & description = a->getDescription();
                const std::string & url = a->getUrl();
                if (!description.empty() && !url.empty()) {
                    theSystem->inform("%s (%s)", description.c_str(),
                                      url.c_str());
                } else if (!description.empty() || !url.empty()) {
                    theSystem->inform("%s", description.length() > 0 ? description.c_str() : url.c_str());
                }
            }
        } else {
            //
            // The parent grouping node is registered for Touch/Drag Sensors.
            //
            Vrml97Node::Group * g = n->toGroup();
            if (g) {
                g->activate(timeStamp, isOver, isActive, point);
                setModified();
            }
        }
    }
}

/**
 * @brief Process events (update the scene).
 *
 * This method should be called after each frame is rendered.
 *
 * @return @c true if the scene needs to be rerendered, @c false otherwise.
 */
bool VrmlScene::update(double currentTime) {
    if (currentTime <= 0.0) { currentTime = theSystem->time(); }
    
    d_deltaTime = DEFAULT_DELTA;
    
    // Update each of the timers.
    std::list<Node *>::iterator i, end = this->d_timers.end();
    for (i = this->d_timers.begin(); i != end; ++i) {
        Vrml97Node::TimeSensor * t = (*i)->toTimeSensor();
        if (t) { t->update(currentTime); }
    }

    // Update each of the clips.
    end = this->d_audioClips.end();
    for (i = this->d_audioClips.begin(); i != end; ++i) {
        Vrml97Node::AudioClip * c = (*i)->toAudioClip();
        if (c) { c->update(currentTime); }
    }
    
    // Update each of the movies.
    end = this->d_movies.end();
    for (i = this->d_movies.begin(); i != end; ++i) {
        Vrml97Node::MovieTexture * m = (*i)->toMovieTexture();
        if (m) { m->update(currentTime); }
    }
    
    //
    // Update each of the scripts.
    //
    std::for_each(this->d_scripts.begin(), this->d_scripts.end(),
                  std::bind2nd(std::mem_fun(&ScriptNode::update), currentTime));

    //
    // Update each of the prototype instances.
    //
    std::for_each(this->protoNodeList.begin(), this->protoNodeList.end(),
                  std::bind2nd(std::mem_fun(&ProtoNode::update), currentTime));
    
    // Pass along events to their destinations
    while (this->d_firstEvent != this->d_lastEvent
            && !this->d_pendingUrl && !this->d_pendingNodes) {
        Event * const e = &this->d_eventMem[this->d_firstEvent];
        this->d_firstEvent = (this->d_firstEvent + 1) % MAXEVENTS;
        
        e->toNode->processEvent(e->toEventIn, *e->value, e->timeStamp);
        
        // this needs to change if event values are shared...
        delete e->value;
    }

# if 0
    if (d_pendingNodes) {
        replaceWorld(*d_pendingNodes, d_pendingScope);
        delete d_pendingNodes;
        d_pendingNodes = 0;
        d_pendingScope = 0;
    } else if (d_pendingUrl) {
        loadUrl(*d_pendingUrl, *d_pendingParameters);
        delete d_pendingUrl;
        delete d_pendingParameters;
        d_pendingUrl = 0;
        d_pendingParameters = 0;
    }
# endif

    // Signal a redisplay if necessary
    return isModified();
}

bool VrmlScene::headlightOn() {
    Vrml97Node::NavigationInfo * const navInfo = bindableNavigationInfoTop();
    if (navInfo) { return navInfo->getHeadlightOn(); }
    return true;
}

/**
 * @brief Draw this scene into the specified viewer
 */
void VrmlScene::render(Viewer * viewer) {
    if (d_newView) {
        viewer->resetUserNavigation();
        d_newView = false;
    }
    
    // Default viewpoint parameters
    float position[3] = { 0.0, 0.0, 10.0 };
    float orientation[4] = { 0.0, 0.0, 1.0, 0.0 };
    float field = 0.785398;
    float avatarSize = 0.25;
    float visibilityLimit = 0.0;

    Vrml97Node::Viewpoint * vp = bindableViewpointTop();
    if (vp) {
        std::copy(vp->getPosition().get(), vp->getPosition().get() + 3, position);
        std::copy(vp->getOrientation().get(), vp->getOrientation().get() + 4,
                  orientation);
        field = vp->getFieldOfView().get();
    }
    
    Vrml97Node::NavigationInfo * ni = bindableNavigationInfoTop();
    if (ni) {
        avatarSize = ni->getAvatarSize()[0];
        visibilityLimit = ni->getVisibilityLimit();
    }

    // Activate the headlight.
    // ambient is supposed to be 0 according to the spec...
    if (headlightOn()) {
        float rgb[3] = { 1.0, 1.0, 1.0 };
        float xyz[3] = { 0.0, 0.0, -1.0 };
        float ambient = 0.3;

        viewer->insertDirLight(ambient, 1.0, rgb, xyz);
    }                         

    // sets the viewpoint transformation
    //
    viewer->setViewpoint(position, orientation, field, avatarSize, visibilityLimit);
    
    // Set background.
    
    Vrml97Node::Background * bg = bindableBackgroundTop();
    if (bg) {
        // Should be transformed by the accumulated rotations above ...
        bg->renderBindable(viewer);
    } else {
        viewer->insertBackground(); // Default background
    }
    
    // Fog
    Vrml97Node::Fog * f = bindableFogTop();
    if (f) {
        viewer->setFog(f->getColor(), f->getVisibilityRange(), f->getFogType().c_str());
    }
    
    // Top level object
    
    viewer->beginObject(0);
    //
    // Hack alert: Right now the rendering code uses the old-style
    // set/unset Transform code, but the culling code accumulates the
    // modelview matrix on the core side using modifications to
    // VrmlTransform and the new VrmlRenderContext class.
    //
    // However, that means we need to jump through some hoops to make
    // sure that the new modelview transform code exactly shadows the
    // old code.
    //
    VrmlMatrix MV; // the modelview transform
    if (vp) {
        VrmlMatrix IM,NMAT;
        vp->inverseTransform(IM);   // put back nested viewpoint. skb
        viewer->MatrixMultiply(IM.get());
        vp->getInverseMatrix(MV);
        viewer->getUserNavigation(NMAT);
        MV = MV.multLeft(NMAT);
        MV = MV.multLeft(IM);
    } else {
        // if there's no viewpoint, then set us up arbitrarily at 0,0,-10,
        // as indicated in the vrml spec (section 6.53 Viewpoint).
        //
        float t[3] = { 0.0f, 0.0f, -10.0f };
        VrmlMatrix NMAT;
        MV.setTranslate(t);
        viewer->getUserNavigation(NMAT);
        MV = MV.multLeft(NMAT);
    }     
    
    VrmlRenderContext rc(BVolume::BV_PARTIAL, MV);
    rc.setDrawBSpheres(true);

    // Do the scene-level lights (Points and Spots)
    std::list<Node *>::iterator li, end = this->d_scopedLights.end();
    for (li = this->d_scopedLights.begin(); li != end; ++li) {
        Vrml97Node::AbstractLight * x = (*li)->toLight();
        if (x) { x->renderScoped(viewer); }
    }
    
    // Render the nodes
    for (size_t i = 0; i < this->nodes.getLength(); ++i) {
        this->nodes.getElement(i)->render(viewer, rc);
    }
    
    viewer->endObject();
    
    // This is actually one frame late...
    d_frameRate = viewer->getFrameRate();
    
    clearModified();

    // If any events were generated during render (ugly...) do an update
    if (eventsPending()) { setDelta(0.0); }
}

/**
 * @brief Indicate that the scene state has changed; need to rerender.
 */
void VrmlScene::setModified() { this->d_modified = true; }

/**
 * @brief Clear the "modified" flag for the scene.
 */
void VrmlScene::clearModified() { this->d_modified = false; }

/**
 * @brief Check if the scene has been modified.
 *
 * @return @c true if the scene has been modified, @c false otherwise.
 */
bool VrmlScene::isModified() const { return this->d_modified; }

/**
 * @brief Set the time until the next update is needed.
 *
 * @param d a time interval.
 */
void VrmlScene::setDelta(const double d) {
    if (d < this->d_deltaTime) { this->d_deltaTime = d; }
}

/**
 * @brief Get the time interval between scene updates.
 *
 * @return the time interval between scene updates.
 */
double VrmlScene::getDelta() const { return this->d_deltaTime; }

/**
 * @brief Get the top node of a BindStack.
 *
 * @return the top node of @p stack.
 */
const NodePtr VrmlScene::bindableTop(const BindStack & stack) {
    return stack.empty() ? NodePtr(0) : stack.front();
}

/**
 * @brief Push a node onto a BindStack.
 *
 * @param stack the BindStack onto which to push @p node.
 * @param node  the Node to push onto @p stack.
 */
void VrmlScene::bindablePush(BindStack & stack, const NodePtr & node) {
    bindableRemove( stack, node ); // Remove any existing reference
    stack.push_front(node);
    setModified();
}

/**
 * @brief Remove a node from a BindStack.
 *
 * @param stack the BindStack from which to remove @p node.
 * @param node  the Node to remove from @p stack.
 */
void VrmlScene::bindableRemove(BindStack & stack, const NodePtr & node) {
    const BindStack::iterator pos = std::find(stack.begin(), stack.end(), node);
    if (pos != stack.end()) {
        stack.erase(pos);
        this->setModified();
    }
}

/**
 * @brief Add a Background node to the list of Background nodes for the scene.
 *
 * @param node  a Background node.
 */
void VrmlScene::addBackground(Vrml97Node::Background & node) {
    this->d_backgrounds.push_back(&node);
}

/**
 * @brief Remove a Background node from the list of Background nodes for the
 *      scene.
 *
 * @param node  a Background node.
 *
 * This method has no effect if @p node is not in the list of Background nodes
 * for the scene.
 */
void VrmlScene::removeBackground(Vrml97Node::Background & node) {
    const std::list<Node *>::iterator end = this->d_backgrounds.end();
    const std::list<Node *>::iterator pos =
            std::find(this->d_backgrounds.begin(), end, &node);
    if (pos != end) { this->d_backgrounds.erase(pos); }
}

/**
 * @brief Get the active node on the bound Background stack.
 *
 * @return the active node on the bound Background stack.
 */
Vrml97Node::Background * VrmlScene::bindableBackgroundTop() {
    Node * const b = bindableTop(d_backgroundStack).get();
    return b ? b->toBackground() : 0;
}

/**
 * @brief Push a Background node onto the bound Background node stack.
 *
 * @param n a Background node.
 */
void VrmlScene::bindablePush(Vrml97Node::Background * n) {
    bindablePush(d_backgroundStack, NodePtr(n));
}

/**
 * @brief Remove a Background node from the bound Background node stack.
 *
 * @param n a Background node.
 */
void VrmlScene::bindableRemove(Vrml97Node::Background * n) {
    bindableRemove(d_backgroundStack, NodePtr(n));
}

/**
 * @brief Add a Fog node to the list of Fog nodes for the scene.
 *
 * @param n a Fog node.
 */
void VrmlScene::addFog(Vrml97Node::Fog & n) { this->d_fogs.push_back(&n); }

/**
 * @brief Remove a Fog node from the list of Fog nodes for the scene.
 *
 * @param node  a Fog node.
 *
 * This method has no effect if @p node is not in the list of Fog nodes for
 * the scene.
 */
void VrmlScene::removeFog(Vrml97Node::Fog & node) {
    const std::list<Node *>::iterator end = this->d_fogs.end();
    const std::list<Node *>::iterator pos =
            std::find(this->d_fogs.begin(), end, &node);
    if (pos != end) { this->d_fogs.erase(pos); }
}

/**
 * @brief Get the active node on the bound Fog stack.
 *
 * @return the active node on the bound Fog stack.
 */
Vrml97Node::Fog * VrmlScene::bindableFogTop() {
    Node * const f = bindableTop(d_fogStack).get();
    return f ? f->toFog() : 0;
}

/**
 * @brief Push a Fog node onto the bound Fog node stack.
 *
 * @param n a Fog node.
 */
void VrmlScene::bindablePush(Vrml97Node::Fog * n) {
    bindablePush(d_fogStack, NodePtr(n));
}

/**
 * @brief Remove a Fog node from the bound Fog node stack.
 *
 * @param n a Fog node.
 */
void VrmlScene::bindableRemove(Vrml97Node::Fog * n) {
    bindableRemove(d_fogStack, NodePtr(n));
}

/**
 * @brief Add a NavigationInfo node to the list of NavigationInfo nodes for the
 *      scene.
 *
 * @param n a NavigationInfo node.
 */
void VrmlScene::addNavigationInfo(Vrml97Node::NavigationInfo & n) {
    this->d_navigationInfos.push_back(&n);
}

/**
 * @brief Remove a NavigationInfo node from the list of NavigationInfo nodes
 *      for the scene.
 *
 * @param node  a NavigationInfo node.
 *
 * This method has no effect if @p node is not in the list of NavigationInfo
 * nodes for the scene.
 */
void VrmlScene::removeNavigationInfo(Vrml97Node::NavigationInfo & node) {
    const std::list<Node *>::iterator end = this->d_navigationInfos.end();
    const std::list<Node *>::iterator pos =
            std::find(this->d_navigationInfos.begin(), end, &node);
    if (pos != end) { this->d_navigationInfos.erase(pos); }
}

/**
 * @brief Get the active node on the bound NavigationInfo stack.
 *
 * @return the active node on the bound NavigationInfo stack.
 */
Vrml97Node::NavigationInfo * VrmlScene::bindableNavigationInfoTop() {
    Node * const n = bindableTop(d_navigationInfoStack).get();
    return n ? n->toNavigationInfo() : 0;
}

/**
 * @brief Push a NavigationInfo node onto the bound NavigationInfo node stack.
 *
 * @param n a NavigationInfo node.
 */
void VrmlScene::bindablePush(Vrml97Node::NavigationInfo * n) {
    bindablePush(d_navigationInfoStack, NodePtr(n));
}

/**
 * @brief Remove a NavigationInfo node from the bound NavigationInfo node stack.
 *
 * @param n a NavigationInfo node.
 */
void VrmlScene::bindableRemove(Vrml97Node::NavigationInfo * n) {
    bindableRemove(d_navigationInfoStack, NodePtr(n));
}

/**
 * @brief Add a Viewpoint node to the list of Viewpoint nodes for the scene.
 *
 * @param n a Viewpoint node.
 */
void VrmlScene::addViewpoint(Vrml97Node::Viewpoint & n) {
    this->d_viewpoints.push_back(&n);
}

/**
 * @brief Remove a Viewpoint node from the list of Viewpoint nodes for the
 *      scene.
 *
 * @param node  a Viewpoint node.
 *
 * This method has no effect if @p node is not in the list of Viewpoint
 * nodes for the scene.
 */
void VrmlScene::removeViewpoint(Vrml97Node::Viewpoint & node) {
    const std::list<Node *>::iterator end = this->d_viewpoints.end();
    const std::list<Node *>::iterator pos =
            std::find(this->d_viewpoints.begin(), end, &node);
    if (pos != end) { this->d_viewpoints.erase(pos); }
}

/**
 * @brief Get the active node on the bound Viewpoint stack.
 *
 * @return the active node on the bound Viewpoint stack.
 */
Vrml97Node::Viewpoint * VrmlScene::bindableViewpointTop() {
    Node * const t = bindableTop(d_viewpointStack).get();
    return t ? t->toViewpoint() : 0;
}

/**
 * @brief Push a Viewpoint node onto the bound Viewpoint node stack.
 *
 * @param n a Viewpoint node.
 */
void VrmlScene::bindablePush(Vrml97Node::Viewpoint * n) {
    bindablePush(d_viewpointStack, NodePtr(n));
    d_newView = true;
}

/**
 * @brief Remove a Viewpoint node from the bound Viewpoint node stack.
 *
 * @param n a Viewpoint node.
 */
void VrmlScene::bindableRemove(Vrml97Node::Viewpoint * n) {
    bindableRemove(d_viewpointStack, NodePtr(n));
    d_newView = true;
}

/**
 * @brief Bind to the next Viewpoint in the list.
 */
void VrmlScene::nextViewpoint() {
    Vrml97Node::Viewpoint *vp = bindableViewpointTop();
    std::list<Node *>::iterator i;

    for (i = d_viewpoints.begin(); i != d_viewpoints.end(); ++i ) {
        if (*i == vp) {
            if (++i == d_viewpoints.end())
              i = d_viewpoints.begin();

            if (*i && (vp = (*i)->toViewpoint())) {
                vp->processEvent("set_bind", SFBool(true), theSystem->time());
            }
            return;
        }
    }
}
  
/**
 * @brief Bind to the previous Viewpoint in the list.
 */
void VrmlScene::prevViewpoint() {
    Vrml97Node::Viewpoint *vp = bindableViewpointTop();
    std::list<Node *>::iterator i;
    
    for (i = d_viewpoints.begin(); i != d_viewpoints.end(); ++i) {
        if (*i == vp) {
            if (i == d_viewpoints.begin()) {
                i = d_viewpoints.end();
            }
            if (*(--i) && (vp = (*i)->toViewpoint())) {
                vp->processEvent("set_bind", SFBool(true), theSystem->time());
            }
            return;
        }
    }
}

/**
 * @brief Get the number of Viewpoint nodes in the scene.
 *
 * @return the number of Viewpoint nodes in the scene.
 */
size_t VrmlScene::nViewpoints() { return d_viewpoints.size(); }

/**
 * @brief Get the name and description of a Viewpoint.
 *
 * @param nvp           the index of the Viewpoint.
 * @retval name         the name of the Viewpoint
 * @retval description  the description of the Viewpoint.
 */
void VrmlScene::getViewpoint(const size_t nvp, std::string & name,
                             std::string & description) {
    std::list<Node *>::const_iterator i = this->d_viewpoints.begin();
    size_t n = 0;
    for (; i != this->d_viewpoints.end(); ++i, ++n ) {
        if (n == nvp) {
            name = (*i)->getId();
            description = (*i)->toViewpoint()->getDescription().get();
            return;
        }
    }
}

/**
 * @brief Bind to a specific Viewpoint.
 *
 * @param name          the name of the Viewpoint to bind to.
 * @param description   the description of the Viewpoint to bind to.
 *
 * This method will only bind to a Viewpoint if both @p name and @p description
 * match the name and description of the Viewpoint. If no such Viewpoint is
 * available, this method has no effect.
 */
void VrmlScene::setViewpoint(const std::string & name,
                             const std::string & description) {
    std::list<Node *>::iterator i = this->d_viewpoints.begin();
    for (; i != this->d_viewpoints.end(); ++i) {
        if (name == (*i)->getId()
                && description == (*i)->toViewpoint()->getDescription().get()) {
            Vrml97Node::Viewpoint * const vp = (*i)->toViewpoint();
            if (vp) {
                vp->processEvent("set_bind", SFBool(true), theSystem->time());
            }
            return;
        }
    }
}

/**
 * @brief Bind to a Viewpoint with a particular index.
 *
 * @param nvp   the index of the Viewpoint to bind to.
 *
 * If @p nvp is not a valid index, this method has no effect.
 */
void VrmlScene::setViewpoint(size_t nvp) {
    std::list<Node *>::iterator i;
    int j = 0;
    
    for (i = d_viewpoints.begin(); i != d_viewpoints.end(); ++i) {
        if (j == nvp) {
            Vrml97Node::Viewpoint * const vp = (*i)->toViewpoint();
            if (vp) {
                vp->processEvent("set_bind", SFBool(true), theSystem->time());
            }
	    return;
        }
        ++j;
    }
}

/**
 * @brief Add a scoped light node to the scene.
 *
 * @param light a light node.
 */
void VrmlScene::addScopedLight(Vrml97Node::AbstractLight & light) {
    this->d_scopedLights.push_back(&light);
}

/**
 * @brief Remove a scoped light node from the scene.
 *
 * @param light the light node to remove.
 *
 * This method has no effect if @p light is not in the list of light nodes for
 * the scene.
 */
void VrmlScene::removeScopedLight(Vrml97Node::AbstractLight & light) {
    this->d_scopedLights.remove(&light);
}

/**
 * @brief Add a MovieTexture node to the scene.
 *
 * @param movie a MovieTexture node.
 */
void VrmlScene::addMovie(Vrml97Node::MovieTexture & movie) {
    this->d_movies.push_back(&movie);
}

/**
 * @brief Remove a MovieTexture node from the scene.
 *
 * @param movie the MovieTexture node to remove.
 *
 * This method has no effect if @p movie is not in the list of MovieTexture
 * nodes for the scene.
 */
void VrmlScene::removeMovie(Vrml97Node::MovieTexture & movie) {
    this->d_movies.remove(&movie);
}

/**
 * @brief Add a Script node to the scene.
 *
 * @param script    a Script node.
 */
void VrmlScene::addScript(ScriptNode & script) {
    this->d_scripts.push_back(&script);
}

/**
 * @brief Remove a Script node from the scene.
 *
 * @param script    the Script node to remove.
 *
 * This method has no effect if @p script is not in the list of Script nodes
 * for the scene.
 */
void VrmlScene::removeScript(ScriptNode & script) {
    this->d_scripts.remove(&script);
}

/**
 * @brief Add a PROTO instance to the scene.
 *
 * @param node  a PROTO instance.
 */
void VrmlScene::addProto(ProtoNode & node) {
    this->protoNodeList.push_back(&node);
}

/**
 * @brief Remove a PROTO instance from the scene.
 *
 * @param node  the PROTO instance to remove.
 *
 * This method has no effect if @p node is not in the list of PROTO instances
 * for the scene.
 */
void VrmlScene::removeProto(ProtoNode & node) {
    this->protoNodeList.remove(&node);
}

/**
 * @brief Add a TimeSensor node to the scene.
 *
 * @param timer a TimeSensor node.
 */
void VrmlScene::addTimeSensor(Vrml97Node::TimeSensor & timer) {
    this->d_timers.push_back(&timer);
}

/**
 * @brief Remove a TimeSensor node from the scene.
 *
 * @param timer the TimeSensor node to remove.
 *
 * This method has no effect if @p timer is not in the list of TimeSensor nodes
 * for the scene.
 */
void VrmlScene::removeTimeSensor(Vrml97Node::TimeSensor & timer) {
    this->d_timers.remove(&timer);
}


/**
 * @brief Add an AudioClip node to the scene.
 *
 * @param audio_clip    an AudioClip node.
 */
void VrmlScene::addAudioClip(Vrml97Node::AudioClip & audio_clip) {
    this->d_audioClips.push_back(&audio_clip);
}

/**
 * @brief Remove an AudioClip node from the scene.
 *
 * @param audio_clip    the AudioClip node to remove.
 *
 * This method has no effect if @p audio_clip is not in the list of AudioClip
 * nodes for the scene.
 */
void VrmlScene::removeAudioClip(Vrml97Node::AudioClip & audio_clip) {
    this->d_audioClips.remove(&audio_clip);
}


/**
 * @brief Propagate the bvolume dirty flag from children to ancestors.
 *
 * The invariant is that if a node's bounding volume is out of date,
 * then the bounding volumes of all that nodes's ancestors must be
 * out of date. However, Node does not maintain a parent pointer. So
 * we must do a traversal of the entire scene graph to do the propagation.
 *
 * @see Node::setBVolumeDirty
 * @see Node::isBVolumeDirty
 */
void VrmlScene::updateFlags()
{
//  Node* root = this->getRoot();
//  root->updateModified(0x002);
}

} // namespace OpenVRML
