#!/bin/bash

./$(dirname $0)/configure -C --disable-static --disable-exception-specs --enable-gtk-doc CXXFLAGS='-Os -Wall -Wextra -Wno-missing-braces -fvisibility=hidden -fvisibility-inlines-hidden' "$*"
