#!/bin/bash

$(dirname $0)/configure -C --prefix=$HOME --disable-static CXX='g++ -pipe' CPPFLAGS="-D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -D_GLIBCXX_CONCEPT_CHECKS -DG_ERRORCHECK_MUTEXES -I$HOME/include -I/usr/lib/jvm/java/include -I/usr/lib/jvm/java/include/linux" CXXFLAGS='-g3 -O0 -Wall -Wextra -Wno-missing-braces -Wno-missing-field-initializers -Wno-long-long' LDFLAGS="-L$HOME/lib64 -L$HOME/lib" JRE_HOME=/usr/lib/jvm/jre "$*"
