#!/bin/bash

./$(dirname $0)/configure -C --prefix=$HOME --disable-static --enable-exception-specs=nothrow CXX='g++ -pipe' CPPFLAGS="-I$HOME/include -I/usr/lib/jvm/java/include -I/usr/lib/jvm/java/include/linux -DNDEBUG" CXXFLAGS='-O3 -Wall -Wextra -Wno-missing-braces -Wno-unused-variable -fvisibility=hidden -fvisibility-inlines-hidden' LDFLAGS="-L$HOME/lib64 -L$HOME/lib" JRE_HOME=/usr/lib/jvm/jre "$*"
