#!/bin/bash

./$(dirname $0)/configure -C --prefix=$HOME --disable-static --enable-exception-specs=nothrow --enable-gtk-doc CXX='g++ -pipe' CPPFLAGS='-I$HOME/include -DNDEBUG' CXXFLAGS='-O3 -Wall -Wextra -Wno-missing-braces -Wno-unused-variable -fvisibility=hidden -fvisibility-inlines-hidden' LDFLAGS='-L$HOME/lib64 -L$HOME/lib' BOOST_LIB_SUFFIX=-mt JAVA_HOME=/usr/lib/jvm/jre "$*"
